/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;



import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Icon;
import javax.swing.JOptionPane;






/**
 *
 * @author agust
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form VistaColaSucia
     */
   
    private boolean estaApagado = true;
    private static Clip clip;
  
    
    public Vista(String titulo) {
        super(titulo);
        establecerIcono();
        initComponents();
        setLocationRelativeTo(null);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonJugar = new javax.swing.JButton();
        JButtonReglas = new javax.swing.JButton();
        jLabelSucia = new javax.swing.JLabel();
        jLabelCola = new javax.swing.JLabel();
        jLabelMazo = new javax.swing.JLabel();
        jLabelPuntaje = new javax.swing.JLabel();
        jLabelImgPaginaPrincipal = new javax.swing.JLabel();
        jButtonSonido = new javax.swing.JButton();
        jTextPaneReglas = new javax.swing.JTextPane();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 375));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonJugar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonJugar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        jButtonJugar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJugar.setText("JUGAR");
        jButtonJugar.setBorder(null);
        jButtonJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJugar.setMaximumSize(new java.awt.Dimension(90, 40));
        jButtonJugar.setMinimumSize(new java.awt.Dimension(90, 40));
        getContentPane().add(jButtonJugar);
        jButtonJugar.setBounds(20, 130, 130, 40);

        JButtonReglas.setBackground(new java.awt.Color(0, 0, 0));
        JButtonReglas.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        JButtonReglas.setForeground(new java.awt.Color(255, 255, 255));
        JButtonReglas.setText("REGLAS");
        JButtonReglas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JButtonReglas.setMaximumSize(new java.awt.Dimension(90, 40));
        JButtonReglas.setMinimumSize(new java.awt.Dimension(90, 40));
        JButtonReglas.setPreferredSize(new java.awt.Dimension(90, 40));
        getContentPane().add(JButtonReglas);
        JButtonReglas.setBounds(20, 190, 130, 40);
        JButtonReglas.getAccessibleContext().setAccessibleName("Reglas");

        jLabelSucia.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        jLabelSucia.setForeground(new java.awt.Color(102, 0, 102));
        jLabelSucia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSucia.setText("SUCIA");
        getContentPane().add(jLabelSucia);
        jLabelSucia.setBounds(370, 180, 160, 40);

        jLabelCola.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        jLabelCola.setForeground(new java.awt.Color(102, 0, 102));
        jLabelCola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCola.setText("COLA ");
        getContentPane().add(jLabelCola);
        jLabelCola.setBounds(380, 120, 160, 60);

        jLabelMazo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMazo.setEnabled(false);
        jLabelMazo.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jLabelMazo);
        jLabelMazo.setBounds(390, 100, 120, 150);

        jLabelPuntaje.setFont(new java.awt.Font("DialogInput", 3, 24)); // NOI18N
        jLabelPuntaje.setForeground(new java.awt.Color(102, 0, 102));
        getContentPane().add(jLabelPuntaje);
        jLabelPuntaje.setBounds(190, 300, 170, 40);

        jLabelImgPaginaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-pagina-principal.png"))); // NOI18N
        jLabelImgPaginaPrincipal.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jLabelImgPaginaPrincipal);
        jLabelImgPaginaPrincipal.setBounds(200, 40, 180, 250);

        jButtonSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sonido_desactivado.png"))); // NOI18N
        jButtonSonido.setBorder(null);
        jButtonSonido.setContentAreaFilled(false);
        jButtonSonido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButtonSonido);
        jButtonSonido.setBounds(460, 290, 40, 40);

        jTextPaneReglas.setEditable(false);
        jTextPaneReglas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextPaneReglas.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        getContentPane().add(jTextPaneReglas);
        jTextPaneReglas.setBounds(200, 100, 170, 160);

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-de-pantalla.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo);
        jLabelFondo.setBounds(-130, -10, 720, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    public void botonJugar(String txtBoton){
        this.jLabelMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dorso-carta.png")));
        this.jLabelMazo.setEnabled(true);
        this.jButtonJugar.setText(txtBoton);
        this.jLabelImgPaginaPrincipal.setIcon(null);
        this.jLabelCola.setText("");
        this.jLabelSucia.setText("");
        this.jLabelPuntaje.setText("PUNTAJE: "+0); 
        this.jTextPaneReglas.setVisible(false);
         
         
       
    }
     public void botonReglas(String txtBoton){
        this.JButtonReglas.setText(txtBoton);
        this.jLabelPuntaje.setText("");
        this.jLabelMazo.setIcon(null);
        reglasTxt("reglas.txt");  
    }
     
    public void botonVolver(){
        this.jLabelImgPaginaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img-pagina-principal.png")));
        this.jLabelMazo.setIcon(null);
        this.jLabelCola.setText("COLA ");
        this.jLabelSucia.setText("SUCIA");
        this.jButtonJugar.setText("JUGAR");
        this.jLabelPuntaje.setText("");
        
    }
    
    public void panelTexto(boolean a){
        this.jTextPaneReglas.setVisible(a);
    }
    public Icon getIconMazo(){
        return this.jLabelMazo.getIcon();
    }
    
    public String getTextBotonJugar(){     
        return this.jButtonJugar.getText();
    }
    public String getTextBotonReglas(){
        return this.JButtonReglas.getText();
    }
    
   public void mostrarPuntos(int puntos){
       this.jLabelPuntaje.setText("PUNTAJE: "+ puntos);
   }
      public void mostrarCarta( Icon carta)
    {
        this.jLabelImgPaginaPrincipal.setIcon(carta);
    }
    
   private void establecerIcono() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.png"));
        setIconImage(icon);
    }
   public void terminaElJuego(){
       
       this.jLabelMazo.setEnabled(false);
       JOptionPane.showMessageDialog(null,"Salió la cola sucia!!"+"\nHasta aca haz llegado amiguito..."+"\nApreta reiniciar para volver a jugar");
   }
 

    public void btnMusica(){
         try {
              if(estaApagado){   
                  AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("src/sonidos/sonidoFondo.wav").getAbsoluteFile());
                  clip = AudioSystem.getClip();
                  clip.open(audioInputStream);    
                  clip.start();       
                  estaApagado=false;
                  this.jButtonSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sonido_activado.png")));
            }else{
                 clip.stop();
                 estaApagado=true;
                 this.jButtonSonido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sonido_desactivado.png")));
        }
         }catch(UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
         System.out.println("Error al reproducir el sonido.");
       }
    }
   
    
    
    
    //////////////LISTENERS/////////////////////
   public void iniciarJuego(ActionListener a1){
      this.jButtonJugar.addActionListener(a1);
      
  }
    public void verReglas(ActionListener a1){
        this.JButtonReglas.addActionListener(a1);
    }
    public void sacarCarta(MouseListener m1){
        this.jLabelMazo.addMouseListener(m1);
    }
      public void sacarCarta(KeyListener k1){
        this.jButtonJugar.addKeyListener(k1);
    }
      public void sonido(ActionListener a1){
        this.jButtonSonido.addActionListener(a1);
       // btnMusica();
      }
    
   public void reglasTxt(String nomArchivo){
       File archivo;
       FileReader fr;
       BufferedReader br;
       try{
           archivo = new File(nomArchivo);
           fr = new FileReader(archivo);
           br = new BufferedReader(fr);
           String linea;
           while((linea = br.readLine()) != null){
               this.jTextPaneReglas.setText(linea);
           }
           br.close();
           fr.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,"Hubo un error de lectura" + e);
       }
   }
   
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonReglas;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonSonido;
    private javax.swing.JLabel jLabelCola;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImgPaginaPrincipal;
    private javax.swing.JLabel jLabelMazo;
    private javax.swing.JLabel jLabelPuntaje;
    private javax.swing.JLabel jLabelSucia;
    private javax.swing.JTextPane jTextPaneReglas;
    // End of variables declaration//GEN-END:variables

   
}
